### ISSUE TITLE
Pidgin crashes regularly when running

### ISSUE THREAD

**Issue by pv** [EionRobb/pidgin-opensteamworks#170]
Pidgin crashes inside the steam plugin, apparently triggered by receiving some message from steam.

Plugin version: 20.20171225git7f761df.fc28
Backtrace:
<details>

```
Core was generated by `pidgin'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fdc61767f4b in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7fdc67741a80 (LWP 2578))]
(gdb) bt full
#0  0x00007fdc61767f4b in raise () at /lib64/libc.so.6
#1  0x00007fdc61752591 in abort () at /lib64/libc.so.6
#2  0x00007fdc617aab0b in __libc_message () at /lib64/libc.so.6
#3  0x00007fdc6183c82d in __fortify_fail_abort () at /lib64/libc.so.6
#4  0x00007fdc6183c863 in  () at /lib64/libc.so.6
#5  0x00007fdc6183a922 in  () at /lib64/libc.so.6
#6  0x00007fdc61839f9b in  () at /lib64/libc.so.6
#7  0x00007fdc617aec51 in __GI__IO_default_xsputn () at /lib64/libc.so.6
#8  0x00007fdc617814c8 in vfprintf () at /lib64/libc.so.6
#9  0x00007fdc6183a03f in __vsprintf_chk () at /lib64/libc.so.6
#10 0x00007fdc61839f6a in __sprintf_chk () at /lib64/libc.so.6
#11 0x00007fdc3e4c96e0 in sprintf (__fmt=0x7fdc3e4caaa8 "%li", __s=0x7fdc3e6ce358 <accountid> "210312952") at /usr/include/bits/stdio2.h:33
        steamid_int = <optimized out>
        accountid = "210312952"
        __func__ = "steam_steamid_to_accountid"
        url = <optimized out>
        accountid = <optimized out>
        __func__ = "steam_get_friend_state"
        personastate = <optimized out>
        steamid = 0x563865a1e860 "119534792437457411"
        message = <optimized out>
        type = <optimized out>
        messages = 0x5638656274c0
        index = 0
        secure = <optimized out>
        server_timestamp = 57254535
        local_timestamp = 1524314187
        users_to_update = 0x5638656772a0
#12 0x00007fdc3e4c96e0 in steam_steamid_to_accountid (steamid=0x563865a1e860 "119534792437457411") at libsteam.c:179
        steamid_int = <optimized out>
        accountid = "210312952"
        __func__ = "steam_steamid_to_accountid"
        url = <optimized out>
        accountid = <optimized out>
        __func__ = "steam_get_friend_state"
        personastate = <optimized out>
        steamid = 0x563865a1e860 "119534792437457411"
        message = <optimized out>
        type = <optimized out>
        messages = 0x5638656274c0
        index = 0
        secure = <optimized out>
        server_timestamp = 57254535
        local_timestamp = 1524314187
        users_to_update = 0x5638656772a0
#13 0x00007fdc3e4c96e0 in steam_get_friend_state (who=0x563865a1e860 "119534792437457411", sa=0x56386589a3f0) at libsteam.c:657
        url = <optimized out>
        accountid = <optimized out>
        __func__ = "steam_get_friend_state"
        personastate = <optimized out>
        steamid = 0x563865a1e860 "119534792437457411"
        message = <optimized out>
        type = <optimized out>
        messages = 0x5638656274c0
        index = 0
        secure = <optimized out>
        server_timestamp = 57254535
        local_timestamp = 1524314187
        users_to_update = 0x5638656772a0
#14 0x00007fdc3e4c96e0 in steam_poll_cb (sa=0x56386589a3f0, obj=0x7fdc28005e10, user_data=0x0) at libsteam.c:779
        personastate = <optimized out>
        steamid = 0x563865a1e860 "119534792437457411"
        message = <optimized out>
        type = <optimized out>
        messages = 0x5638656274c0
        index = 0
        secure = <optimized out>
        server_timestamp = 57254535
        local_timestamp = 1524314187
        users_to_update = 0x5638656772a0
#15 0x00007fdc3e4c4149 in steam_connection_process_data (steamcon=0x5638656e1e00) at steam_connection.c:243
        root = <optimized out>
        jsonobj = 0x7fdc28005e10
        parser = 0x56386528d500
        len = <optimized out>
        tmp = 0x5638659fb600 "{\"pollid\":0,\"messages\":[{\"type\":\"personastate\",\"timestamp\":57254535,\"utc_timestamp\":1524314187,\"steamid_from\":\"119534792437457411\",\"status_flags\":1106,\"persona_name\":\"aaaaaaaaa\"}],\"messagelast\":15,\"ti"...
        steamcon = 0x5638656e1e00
        sa = 0x56386589a3f0
        buf = "HTTP/1.0 200 OK\r\nContent-Type: application/json; charset=UTF-8\r\nContent-Length: 290\r\nExpires: Sat, 21 Apr 2018 12:36:27 GMT\r\nDate: Sat, 21 Apr 2018 12:36:27 GMT\r\nConnection: close\r\n\r\n{\"pollid\":0,\"mess"...
        len = <optimized out>
#16 0x00007fdc3e4c4149 in steam_post_or_get_readdata_cb (data=0x5638656e1e00, source=<optimized out>, cond=<optimized out>) at steam_connection.c:344
        steamcon = 0x5638656e1e00
        sa = 0x56386589a3f0
        buf = "HTTP/1.0 200 OK\r\nContent-Type: application/json; charset=UTF-8\r\nContent-Length: 290\r\nExpires: Sat, 21 Apr 2018 12:36:27 GMT\r\nDate: Sat, 21 Apr 2018 12:36:27 GMT\r\nConnection: close\r\n\r\n{\"pollid\":0,\"mess"...
        len = <optimized out>
#17 0x0000563864e0c2c2 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x5638659db1b0) at gtkeventloop.c:73
        closure = 0x5638659db1b0
        purple_cond = PURPLE_INPUT_READ
#18 0x00007fdc627737cd in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#19 0x00007fdc62773b98 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#20 0x00007fdc62773ec2 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#21 0x00007fdc662b895f in gtk_main () at /lib64/libgtk-x11-2.0.so.0
#22 0x0000563864dd18b3 in main (argc=<optimized out>, argv=<optimized out>) at gtkmain.c:939
        opt_force_online = 0
        opt_help = <optimized out>
        opt_login = 0
        opt_nologin = 0
        opt_version = <optimized out>
        opt_si = <optimized out>
        opt_config_dir_arg = 0x0
        opt_login_arg = 0x0
        opt_session_arg = 0x0
        search_path = <optimized out>
        accounts = <optimized out>
        sig_indx = 1
        sigset = {__val = {91142, 0 <repeats 15 times>}}
        errmsg = '\000' <repeats 1497 times>...
        signal_channel = <optimized out>
        signal_status = <optimized out>
        signal_channel_watcher = 1
        segfault_message_tmp = <optimized out>
        error = 0x0
        opt = <optimized out>
        gui_check = <optimized out>
        debug_enabled = <optimized out>
        migration_failed = 0
        active_accounts = <optimized out>
        long_options = 
            {{name = 0x563864e70251 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x563864e5e599 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x563864e6c23b "force-online", has_arg = 0, flag = 0x0, val = 102}, {name = 0x563864e600c6 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x563864e6c0e5 "login", has_arg = 2, flag = 0x0, val = 108}, {name = 0x563864e6c248 "multiple", has_arg = 0, flag = 0x0, val = 109}, {name = 0x563864e6c251 "nologin", has_arg = 0, flag = 0x0, val = 110}, {name = 0x563864e70247 "session", has_arg = 1, flag = 0x0, val = 115}, {name = 0x563864e6283d "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x563864e7025a "display", has_arg = 1, flag = 0x0, val = 68}, {name = 0x563864e6cd2a "sync", has_arg = 0, flag = 0x0, val = 83}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
(gdb) quit
```

</details>

**Comment by pv** [comment]
sorry, same as #169
