### ISSUE TITLE
ABRT from steam_post_or_get_readdata_cb 

### ISSUE THREAD

**Issue by undeference** [EionRobb/pidgin-opensteamworks#177]
https://retrace.fedoraproject.org/faf/reports/2280854/

**Comment by EionRobb** [comment]
Unfortunately I can't do much with that.  Can you use https://developer.pidgin.im/wiki/GetABacktrace to get a full debug backtrace?

**Comment by EionRobb** [comment]
That does help thanks :)

This should have been fixed in https://github.com/EionRobb/pidgin-opensteamworks/commit/15a6528d7a31189a19d9eef96655326ada210bf4 ?  Are you running from version 1.6.1 or self-compile from git?

**Comment by undeference** [comment]
I am using the upstream Fedora build: pidgin-libsteam-1.6.1-23.20180801gitb16a636.fc28.noarch
Presumably built from git revision b16a636 from 2018-08-01

**Comment by EionRobb** [comment]
Can you try building from git and see if that fixes the crashing?

**Comment by undeference** [comment]
I built it myself from git (not that it should make a difference when the source is the same) and was able to reproduce it. Things look a little different in the backtrace

```
#4  0x00007f848a1e5f91 in steam_post_or_get (sa=0xae, method=(unknown: 2457351808), host=0x5613efb929c0 "P\353Z\357\023V", url=0x5613ef5fc300 "p%\202\356\023V", postdata=0x5613efdceda0 "<html><head><title>Unauthorized</title></head><body><h1>Unauthorized</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>", callback_func=0xae88fa45c9, user_data=0x5613ef5ff5a0, keepalive=0) at steam_connection.c:601
        request = 0x5613ef9690e0
        cookies = 0x5613efdceda0 "<html><head><title>Unauthorized</title></head><body><h1>Unauthorized</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>"
        steamcon = <optimized out>
        real_url = 0xa0a2c7f41d367000 <error: Cannot access memory at address 0xa0a2c7f41d367000>
        is_proxy = 1
        user_agent = 0xfa <error: Cannot access memory at address 0xfa>
        languages = <optimized out>
        language_names = <optimized out>
        proxy_info = 0x7f847d7d0418 <sftk_FreeObject+40>
        proxy_auth = <optimized out>
---Type <return> to continue, or q <return> to quit---
        proxy_auth_base64 = <optimized out>
```

**Comment by undeference** [comment]
After that, I get

```
#6  0x00007f2fdaf4decb in steam_post_or_get_readdata_cb (data=0x555d32468f70, source=<optimized out>, cond=<optimized out>) at steam_connection.c:349
        steamcon = 0x555d32468f70
        sa = 0x555d31c23290
        buf = "HTTP/1.0 401 Unauthorized\r\nContent-Length: 174\r\nContent-Type: text/html; charset=UTF-8\r\nExpires: Thu, 20 Sep 2018 19:45:51 GMT\r\nCache-Control: max-age=0, no-cache, no-store\r\nPragma: no-cache\r\nDate: Th"...
        len = 424
```
and then another

```
#11 0x00007faded9a5ea5 in steam_post_or_get_readdata_cb (data=0x562a035d6e90, source=<optimized out>, cond=<optimized out>) at steam_connection.c:361
        steamcon = 0x562a035d6e90
        sa = 0x562a035d60c0
        buf = "HTTP/1.0 429 Too Many Requests\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Length: 108\r\nExpires: Thu, 20 Sep 2018 19:45:56 GMT\r\nCache-Control: max-age=0, no-cache, no-store\r\nPragma: no-cache\r\nDat"...
        len = <optimized out>
```
