### ISSUE TITLE
Pidgin crashes when steam client is started

### ISSUE THREAD

**Issue by undeference** [EionRobb/pidgin-opensteamworks#185]
I thought this might be the same as #169 but the backtrace is different

```
#6  0x00007f442eb7ee5d in g_str_equal (v1=v1@entry=0x0, v2=<optimized out>)
    at ../glib/ghash.c:2292
        string1 = 0x0
        string2 = <optimized out>
#7  0x00007f441d37fc2a in steam_got_friend_summaries
    (sa=0x55aad45fbe50, obj=<optimized out>, user_data=<optimized out>)
    at libsteam.c:879
        player = 0x55aad5a8cd90
        steamid = 0x0
        personastate = -1
        players = 0x55aad5106160
        buddy = <optimized out>
        sbuddy = <optimized out>
        index = 41
#8  0x00007f441d37e9ca in steam_connection_process_data
    (steamcon=0x55aad53fc410) at steam_connection.c:270
        root = <optimized out>
        jsonobj = 0x55aad52624a0
        parser = 0x55aad5af3560 [JsonParser]
        len = <optimized out>
        tmp = 0x55aad5c25540 "{\"players\":[{\"steamid\":\"76561198016883184\",\"communityvisibilitystate\":3,\"profilestate\":1,\"personaname\":\"AwesomeKabi\",\"lastlogoff\":1514864386,\"commentpermission\":1,\"profileurl\":\"https://steamcommunity."...
        steamcon = 0x55aad53fc410
        sa = 0x55aad45fbe50
        buf = "/\003\030I91\022\b\a\242(\v\324J]sfH\001\212\352\211\313\002({6a\030\356\333u֣Ąa\214\021\302\304\071\064\224\363\223\212\367aq\r\346\363\266\257C\017\232\061\302\330\061\063\021\316PV\b\362\205+\271\355\071\265\336i\226\320ҔT\n\310\365)T:\264\071\r\rDB\356\327_ӱ,@Q=\310W\000\345\002M\037r\205\243\036KzZ7|x\037f\aw\373;\257\343\031E\367Q\024\334\315\375\022A\264\036&\213\nDo\205+\251\310(\001Δ\017\312\000%Z\345\061\261\226\333(s\323d*\204\221\065s-\005(\252\023\275\v\240\f\235T\036'x\325\330,\273fz\322\334X\315\016\342\071\323\312\025E3\307"...
        len = <optimized out>
#9  0x00007f441d37e9ca in steam_post_or_get_readdata_cb (data=0x55aad53fc410, source=<optimized out>, cond=<optimized out>) at steam_connection.c:371
        steamcon = 0x55aad53fc410
        sa = 0x55aad45fbe50
        buf = "/\003\030I91\022\b\a\242(\v\324J]sfH\001\212\352\211\313\002({6a\030\356\333u֣Ąa\214\021\302\304\071\064\224\363\223\212\367aq\r\346\363\266\257C\017\232\061\302\330\061\063\021\316PV\b\362\205+\271\355\071\265\336i\226\320ҔT\n\310\365)T:\264\071\r\rDB\356\327_ӱ,@Q=\310W\000\345\002M\037r\205\243\036KzZ7|x\037f\aw\373;\257\343\031E\367Q\024\334\315\375\022A\264\036&\213\nDo\205+\251\310(\001Δ\017\312\000%Z\345\061\261\226\333(s\323d*\204\221\065s-\005(\252\023\275\v\240\f\235T\036'x\325\330,\273fz\322\334X\315\016\342\071\323\312\025E3\307"...
        len = <optimized out>
```

**Comment by EionRobb** [comment]
That's a weird one.  I wonder what kind of friend profile doesn't have a steam ID.

Can you try with that commit?

**Comment by undeference** [comment]
I haven't seen it again in several hours, so I assume you fixed it unless I see it again.
